# Summary Statistics and Exploration of Current State of Electricians

We're about to have a fun time trying to navigate this Excel file.

In [15]:
import pandas as pd
import numpy as np
from plotnine import *
import seaborn as sns
import statsmodels.api as sm
from great_tables import GT
import requests
from io import StringIO
import openpyxl as xl

In [28]:
df = pd.read_excel('../raw-data/OEWS_Electricians-05-24.xlsx', skiprows = 5)

df.head()

/Users/kevinphan981/Programming/electrician-policy/.venv/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default

,Area Name,Employment (1),Employment percent relative standard error (3),Hourly mean wage,Annual mean wage (2),Wage percent relative standard error (3),Hourly 10th percentile wage,Hourly 25th percentile wage,Hourly median wage,Hourly 75th percentile wage,Hourly 90th percentile wage,Annual 10th percentile wage (2),Annual 25th percentile wage (2),Annual median wage (2),Annual 75th percentile wage (2),Annual 90th percentile wage (2),"Employment per 1,000 jobs",Location Quotient
0,"Abilene, TX (00-10180)",460.0,6.4,24.62,51200.0,1.7,17.31,19.33,22.84,28.91,31.55,36010.0,40200.0,47500.0,60140.0,65620.0,6.240,1.30
1,"Aguadilla, PR (00-10380)",60.0,26.5,19.25,40040.0,10.4,10.38,11.85,16.26,25.04,29.21,21580.0,24650.0,33810.0,52080.0,60760.0,1.317,0.27
2,"Akron, OH (00-10420)",1430.0,3.6,36.00,74890.0,6.2,18.72,25.14,35.80,45.00,57.79,38940.0,52280.0,74470.0,93600.0,120190.0,4.480,0.93
3,Alaska nonmetropolitan area (02-00006),650.0,7.5,42.27,87910.0,2.0,24.50,29.66,40.58,50.01,61.25,50960.0,61680.0,84400.0,104010.0,127400.0,6.051,1.26
4,"Albany, GA (00-10500)",310.0,7.8,28.28,58820.0,2.4,17.36,22.26,28.39,36.69,37.45,36110.0,46310.0,59050.0,76310.0,77900.0,5.280,1.10

In [32]:
df.describe()

,Employment (1),Employment percent relative standard error (3),Hourly mean wage,Annual mean wage (2),Wage percent relative standard error (3),Hourly 10th percentile wage,Hourly 25th percentile wage,Hourly median wage,Hourly 75th percentile wage,Hourly 90th percentile wage,Annual 10th percentile wage (2),Annual 25th percentile wage (2),Annual median wage (2),Annual 75th percentile wage (2),Annual 90th percentile wage (2),"Employment per 1,000 jobs",Location Quotient
count,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000,527.000000
mean,1355.654649,6.825996,31.312106,65128.045541,2.344213,19.564288,24.000114,30.606053,37.457571,43.491935,40692.390892,49918.690702,63659.259962,77910.341556,90461.935484,4.870304,1.011290
std,3057.168397,2.926045,5.318800,11063.135620,1.295121,2.778085,3.880860,5.891978,7.374696,8.865790,5778.199423,8071.968065,12254.867521,15339.543691,18440.831144,1.899657,0.394629
min,40.000000,1.400000,18.350000,38170.000000,0.500000,10.380000,11.850000,15.640000,22.600000,27.500000,21580.000000,24650.000000,32540.000000,47020.000000,57190.000000,1.313000,0.270000
25%,290.000000,5.000000,27.265000,56715.000000,1.600000,17.770000,21.970000,26.895000,30.930000,36.825000,36960.000000,45695.000000,55940.000000,64335.000000,76595.000000,3.674000,0.760000
50%,500.000000,6.300000,30.470000,63380.000000,2.100000,18.680000,23.130000,29.390000,36.690000,42.150000,38850.000000,48120.000000,61120.000000,76310.000000,87660.000000,4.534000,0.940000
75%,1015.000000,8.050000,34.845000,72470.000000,2.800000,21.780000,26.595000,35.365000,41.725000,48.745000,45305.000000,55315.000000,73555.000000,86780.000000,101400.000000,5.738500,1.190000
max,38890.000000,26.500000,50.120000,104240.000000,13.300000,28.430000,37.530000,52.280000,63.040000,86.090000,59130.000000,78060.000000,108740.000000,131120.000000,179060.000000,17.688000,3.670000